const Relations = {
    MALE: 0,
    FEMALE: 1,

    RELATIONS: new Map([
        ["AUNT", ["NEPHEW", "NICE"]],
        ["BOYFRIEND", [null, "GIRLFRIEND"]],
        ["BROTHER", ["BROTHER", "SISTER"]],
        ["BROTHER_IN_LAW", ["BROTHER_IN_LAW", "SISTER_IN_LAW"]],
        ["COLLEAGUE", ["COLLEAGUE", "COLLEAGUE"]],
        ["COUSIN", ["COUSIN", "COUSIN"]],
        ["DAUGHTER", ["FATHER", "MOTHER"]],
        ["DAUGHTER_IN_LAW", ["FATHER_IN_LAW", "MOTHER_IN_LAW"]],
        ["ENEMY", ["ENEMY", "ENEMY"]],
        ["FATHER", ["SON", "DAUGHTER"]],
        ["FATHER_IN_LAW", ["SON_IN_LAW", "DAUGHTER_IN_LAW"]],
        ["FRIEND", ["FRIEND", "FRIEND"]],
        ["GIRLFRIEND", ["BOYFRIEND", "BOYFRIEND"]],
        ["GRANDDAUGHTER", ["GRANDFATHER", "GRANDMOTHER"]],
        ["GRANDFATHER", ["GRANDSON", "GRANDDAUGHTER"]],
        ["GRANDMOTHER", ["GRANDSON", "GRANDDAUGHTER"]],
        ["GRANDSON", ["GRANDFATHER", "GRANDMOTHER"]],
        ["HUSBAND", [null, "WIFE"]],
        ["KING", ["SUBJECT", "SUBJECT"]],
        ["LANDLORD", "TENANT", "TENANT"],
        ["MAID", ["MASTER", "MISTRESS"]],
        ["MASTER", ["SERVANT", "MAID"]],
        ["MENTEE", ["MENTOR", "MENTOR"]],
        ["MENTOR", ["MENTEE", "MENTEE"]],
        ["MISTRESS", ["SERVANT", "MAID"]],
        ["MOTHER", ["SON", "DAUGHTER"]],
        ["MOTHER_IN_LAW", ["SON_IN_LAW", "DAUGHTER_IN_LAW"]],
        ["NEIGHBOR", ["NEIGHBOR", "NEIGHBOR"]],
        ["NEPHEW", ["UNCLE", "AUNT"]],
        ["NICE", ["UNCLE", "AUNT"]],
        ["SERVANT", ["MASTER", "MISTRESS"]],
        ["SISTER", ["BROTHER", "SISTER"]],
        ["SISTER_IN_LAW", ["BROTHER_IN_LAW", "SISTER_IN_LAW"]],
        ["SON", ["FATHER", "MOTHER"]],
        ["SON_IN_LAW", ["FATHER_IN_LAW", "MOTHER_IN_LAW"]],
        ["STEP_BROTHER", ["STEP_BROTHER", "STEP_SISTER"]],
        ["STEP_DAUGHTER", ["STEP_FATHER", "STEP_MOTHER"]],
        ["STEP_FATHER", ["STEP_SON", "STEP_DAUGHTER"]],
        ["STEP_MOTHER", ["STEP_SON", "STEP_DAUGHTER"]],
        ["STEP_SISTER", ["STEP_BROTHER", "STEP_SISTER"]],
        ["STEP_SON", ["STEP_FATHER", "STEP_MOTHER"]],
        ["SUBJECT", ["KING", "KING"]],
        ["STUDENT", ["TEACHER", "TEACHER"]],
        ["TEACHER", ["STUDENT", "STUDENT"]],
        ["TENANT", ["LANDLORD", "LANDLORD"]],
        ["UNCLE", ["NEPHEW", "NICE"]],
        ["WIFE", ["HUSBAND", null]]
    ]),

    SELF: {
        FATHER: [],
    },

    FATHER: {
        FATHER: "GRANDFATHER",
        MOTHER: "GRANDMOTHER",
        UNCLE: "GRANDFATHER",
        AUNTY: "GRANDMOTHER",
        WIFE: "MOTHER",
        BROTHER: "UNCLE",
        BROTHER_IN_LAW: "UNCLE",
        SISTER: "AUNTY",
        SISTER_IN_LAW: "AUNTY",
        NEPHEW: "COUSIN",
        NICE: "COUSIN",
        SON: "BROTHER",
        DAUGHTER: "SISTER",
        GRANDFATHER: "GREAT_GRANDFATHER",
        GRANDMOTHER: "GREAT_GRANDMOTHER",
        GRANDSON: "SON",
        GRANDDAUGHTER: "DAUGHTER",
    },

    MOTHER: {
        FATHER: "GRANDFATHER",
        UNCLE: "GRANDFATHER",
        MOTHER: "GRANDMOTHER",
        AUNTY: "GRANDMOTHER",
        HUSBAND: "FATHER",
        BROTHER: "UNCLE",
        SISTER: "AUNTY",
        NEPHEW: "BROTHER",
        NICE: "SISTER",
        SON: "BROTHER",
        DAUGHTER: "SISTER",
        GRANDFATHER: "GREAT_GRANDFATHER",
        GRANDMOTHER: "GREAT_GRANDMOTHER",
        GRANDSON: "SON",
        GRANDDAUGHTER: "DAUGHTER",
    },

    UNCLE: {
        FATHER: "GRANDFATHER",
        UNCLE: "GRANDFATHER",
        MOTHER: "GRANDMOTHER",
        AUNTY: "GRANDMOTHER",
        WIFE: "AUNTY",
        BROTHER_IN_LAW: "UNCLE",
        SISTER: "AUNTY",
        SON: "COUSIN",
        DAUGHTER: "COUSIN",
        GRANDFATHER: "GREAT_GRANDFATHER",
        GRANDMOTHER: "GREAT_GRANDMOTHER",
        GRANDSON: "GRANDSON",
        GRANDDAUGHTER: "GRANDDAUGHTER",
    },

    AUNTY: {
        FATHER: "GRANDFATHER",
        UNCLE: "GRANDFATHER",
        MOTHER: "GRANDMOTHER",
        AUNTY: "GRANDMOTHER",
        HUSBAND: "UNCLE",
        BROTHER: "UNCLE",
        SISTER_IN_LAW: "AUNTY",
        SON: "COUSIN",
        DAUGHTER: "COUSIN",
        GRANDFATHER: "GREAT_GRANDFATHER",
        GRANDMOTHER: "GREAT_GRANDMOTHER",
        GRANDSON: "GRANDSON",
        GRANDDAUGHTER: "GRANDDAUGHTER",
    },

    HUSBAND: {
        FATHER: "FATHER_IN_LAW",
        UNCLE: "UNCLE_IN_LAW",
        MOTHER: "MOTHER_IN_LAW",
        AUNTY: "AUNTY_IN_LAW",
        BROTHER: "BROTHER_IN_LAW",
        SISTER: "SISTER_IN_LAW",
        NEPHEW: "NEPHEW",
        NICE: "NICE",
        SON: "SON",
        DAUGHTER: "DAUGHTER",
        GRANDFATHER: "GRANDFATHER_IN_LAW",
        GRANDMOTHER: "GRANDMOTHER_IN_LAW",
        GRANDSON: "GRANDSON",
        GRANDDAUGHTER: "GRANDDAUGHTER",
    },

    WIFE: {
        FATHER: "FATHER_IN_LAW",
        UNCLE: "UNCLE_IN_LAW",
        MOTHER: "MOTHER_IN_LAW",
        AUNTY: "AUNTY_IN_LAW",
        BROTHER: "BROTHER_IN_LAW",
        SISTER: "SISTER_IN_LAW",
        NEPHEW: "NEPHEW",
        NICE: "NICE",
        SON: "SON",
        DAUGHTER: "DAUGHTER",
        GRANDFATHER: "GRANDFATHER_IN_LAW",
        GRANDMOTHER: "GRANDMOTHER_IN_LAW",
        GRANDSON: "GRANDSON",
        GRANDDAUGHTER: "GRANDDAUGHTER",
    },

    BROTHER: {
        FATHER: "FATHER",
        UNCLE: "UNCLE",
        MOTHER: "MOTHER",
        AUNTY: "AUNTY",
        WIFE: "SISTER_IN_LAW",
        BROTHER: "BROTHER",
        SISTER: "SISTER",
        NEPHEW: "NEPHEW",
        NICE: "NICE",
        SON: "NEPHEW",
        DAUGHTER: "NICE",
        GRANDFATHER: "GRANDFATHER",
        GRANDMOTHER: "GRANDMOTHER",
        GRANDSON: "GRANDSON",
        GRANDDAUGHTER: "GRANDDAUGHTER",
    },

    SISTER: {
        FATHER: "FATHER",
        UNCLE: "UNCLE",
        MOTHER: "MOTHER",
        AUNTY: "AUNTY",
        HUSBAND: "BROTHER_IN_LAW",
        BROTHER: "BROTHER",
        SISTER: "SISTER",
        NEPHEW: "NEPHEW",
        NICE: "NICE",
        SON: "NEPHEW",
        DAUGHTER: "NICE",
        GRANDFATHER: "GRANDFATHER",
        GRANDMOTHER: "GRANDMOTHER",
        GRANDSON: "GRANDSON",
        GRANDDAUGHTER: "GRANDDAUGHTER",
    },

    SON: {
        FATHER: "HUSBAND",
        MOTHER: "WIFE",
        UNCLE: "BROTHER",
        AUNTY: "AUNTY",
        WIFE: "DAUGHTER_IN_LAW",
        BROTHER: "SON",
        SISTER: "DAUGHTER",
        NEPHEW: "GRANDSON",
        NICE: "GRANDDAUGHTER",
        SON: "GRANDSON",
        DAUGHTER: "GRANDDAUGHTER",
        GRANDFATHER: "GRANDFATHER",
        GRANDMOTHER: "GRANDMOTHER",
        GRANDSON: "GREAT_GRANDSON",
        GRANDDAUGHTER: "GREAT_GRANDDAUGHTER",
    },

    DAUGHTER: {
        FATHER: "HUSBAND",
        MOTHER: "WIFE",
        UNCLE: "BROTHER",
        AUNTY: "AUNTY",
        HUSBAND: "SON_IN_LAW",
        BROTHER: "SON",
        SISTER: "DAUGHTER",
        NEPHEW: "GRANDSON",
        NICE: "GRANDDAUGHTER",
        SON: "GRANDSON",
        DAUGHTER: "GRANDDAUGHTER",
        GRANDFATHER: "GRANDFATHER",
        GRANDMOTHER: "GRANDMOTHER",
        GRANDSON: "GREAT_GRANDSON",
        GRANDDAUGHTER: "GREAT_GRANDDAUGHTER",
    },
}

export default Relations;